CREATE DATABASE IF NOT EXISTS Loja;

USE Loja;

CREATE TABLE Loja . Clientes (
    idCliente INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Endereco VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NULL DEFAULT NULL,
    Telefone INT(11) NULL DEFAULT NULL,
    CPF INT(11) NOT NULL,
    PRIMARY KEY (idCliente)
);

CREATE TABLE Loja . Produtos (
    idProduto INT NOT NULL AUTO_INCREMENT,
    
)